version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: dsa75_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dsa_user
      POSTGRES_PASSWORD: dsa_password
      POSTGRES_DB: dsa75_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
